/**
 * The Symbol Table builder.
 * @module src/symbolTable
 */

/**
 * Build the Symbol Table based on the tokenlist generated by the tokenizer.
 * @param {Token[]} tokenList - The Token list generated from the tokenizer.
 * @returns {SymbolTable} The Symbol Table.
 */
module.exports = function(tokenList){

};